### ISSUE TITLE
保存api模板时参数的value没有填写，这个参数会被过滤无法保存

### ISSUE THREAD

**Issue by AzoraLeo** [yinquanwang/FasterWeb#18]
api模板的作用应该只是一个格式，不需要填值都ok的，具体的值应该在用例里面写
![image](https://user-images.githubusercontent.com/42163435/50585735-60f24080-0eb1-11e9-98a9-b4fdcd982505.png)

**Comment by yinquanwang** [comment]
默认是这样设置的

**Comment by AzoraLeo** [comment]
> 默认是这样设置的
但是感觉并不合理呀

**Comment by yinquanwang** [comment]
下个版本优化下

**Comment by yinquanwang** [comment]
已修复
