### ISSUE TITLE
在项目里面刷新，左侧导航被影藏

### ISSUE THREAD

**Issue by Zimucasey** [yinquanwang/FasterWeb#2]
提个小建议，在项目里面，进行刷新，不影藏导航栏，不然需要回到项目首页重新进入项目
![image](https://user-images.githubusercontent.com/27843545/46202907-ab13d500-c34a-11e8-9812-a2375ac4d996.png)

**Comment by yinquanwang** [comment]
这个后面会修复哈，小细节还没来得及处理

**Comment by yinquanwang** [comment]
已修复
